const express = require('express')
const { addBook, listBook, listBookFromStore, addBookCopy, addCategory, listCategory, showBookInfo, listBookCopy, addCategoryOfBook, listCategoryOfBook, showBookInfoPoppulateStore, addBookPref } = require('../Controllers/book')
const { auth } = require('../Middleware/auth')
const { upload } = require('../Middleware/upload')
const router = express.Router()

router.post('/addbook/:id', auth, upload, addBook)
router.get('/listbook', listBook)
router.get('/listbook/:id', listBookFromStore)
router.get('/showbookinfo/:id', showBookInfo)
router.get('/showbookinfopopstore/:id', showBookInfoPoppulateStore)
router.post('/bookcopy/:id', addBookCopy)
router.post('/addcategory', addCategory)
router.get('/listcategory', listCategory)
router.get('/listbookcopy/:id', listBookCopy)
router.post('/addcategoryofbook', addCategoryOfBook)
router.get('/listcategoryofbook', listCategoryOfBook)
router.post('/addbookpref/:id', addBookPref)
module.exports = router