const { addOrder, listOrderForAcc, showOrderForAcc, addUploadPayment, listItemForCheck, orderForCheck, orderConfirmCheck, listItemForShipping, addShippingDay, orderForShipping, listWaitForShipping, listItemForReturn, orderForReturn, listShipped, confirmReceiveBook, listWaitForReturn, addReturnInfo, confirmOrderComplete, listOrderSuccessUser } = require('../Controllers/order')
const express = require('express')
const { auth } = require('../Middleware/auth')
const { upload } = require('../Middleware/upload')
const router = express.Router()

router.post('/addorder/:id', auth, addOrder)
router.get('/showorder/:id', auth, showOrderForAcc)
router.get('/listorderuser/:id', auth, listOrderForAcc)
router.post('/uploadpayment/:id', auth, upload, addUploadPayment)
router.get('/listorderforcheckpayment/:id', auth, listItemForCheck)
router.get('/orderforcheck/:id', auth, orderForCheck)
router.post('/orderconfirmcheck/:id', auth, orderConfirmCheck)
router.get('/listorderforshipping/:id', auth, listItemForShipping)
router.get('/orderforshipping/:id', auth, orderForShipping)
router.post('/addshippingday/:id', auth, addShippingDay)
router.get('/listwaitforshipping/:id', auth, listWaitForShipping)
router.get('/listbookforreturn/:id', auth, listItemForReturn)
router.get('/orderforreturn/:id', auth, orderForReturn)
router.get('/listshipped/:id', auth, listShipped)
router.put('/confirmreceivebook/:id', auth, confirmReceiveBook)
router.get('/listreturn/:id', auth, listWaitForReturn)
router.put('/addreturninfo/:id', auth, addReturnInfo)
router.put('/confirmordercomplete/:id', auth, confirmOrderComplete)
router.get('/listordersuccessuser/:id', auth, listOrderSuccessUser)
module.exports = router